service: place-proxy-api

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, "dev"}
  region: eu-west-2
  memorySize: 128

  environment:
    REGION: ${self:provider.region}

functions:
  place-proxy:
    handler: events/place-proxy.handler
    events:
      - http:
          path: /{department}
          method: get
          authorizer: aws_iam
          cors: true
          request:
            parameters:
              paths:
                department: true
      - http:
          path: /{department}/{city}
          method: get
          authorizer: aws_iam
          cors: true
          request:
            parameters:
              paths:
                city: true
                department: true
# custom:
#   domains:
#     dev: dev-api.la-foulee.com
#     production: api.la-foulee.com
#   customDomain:
#     domainName: ${self:custom.domains.${self:provider.stage}}
#     basePath: "place-proxy"
#     stage: "${self:provider.stage}"
#     createRoute53Record: true
